"use client";

import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, ArrowDown, ArrowUp, Check, Eye, EyeOff, Pencil, Plus, Tags } from "lucide-react";
import { apiFetch } from "@/lib/api";
import type { TodoCategoryDto } from "@/lib/types";
import { TODO_CATEGORIES } from "@/lib/todo-options";
import { useSession } from "@/components/app-providers";
import { AuthGate, EmptyState, ErrorState, ListSkeleton } from "@/components/states";
import { Sheet } from "@/components/sheet";
import { TodoSectionNav } from "@/components/todo-section-nav";

const colors = [{ value: "aqua", label: "민트" }, { value: "blush", label: "핑크" }, { value: "butter", label: "옐로" }, { value: "lilac", label: "라일락" }];

function CategoryEditor({ category, onClose, onSaved }: { category?: TodoCategoryDto | null; onClose: () => void; onSaved: () => void }) {
  const [name, setName] = useState(category?.name ?? "");
  const [baseCategory, setBaseCategory] = useState(category?.baseCategory ?? "생활");
  const [color, setColor] = useState(category?.color ?? "lilac");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { await apiFetch(category ? `/me/todo-categories/${category.id}` : "/me/todo-categories", { method: category ? "PATCH" : "POST", body: JSON.stringify({ name, baseCategory, color, icon: "tag" }) }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "카테고리를 저장하지 못했어요."); } finally { setSaving(false); } };
  return <Sheet title={category ? "카테고리 편집" : "새 카테고리"} onClose={onClose}><form className="composer-form category-editor" onSubmit={submit}><label className="field"><span>카테고리 이름</span><input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="예: 헬스장" maxLength={30} required /><small>내 TODO에 표시되는 이름이에요.</small></label><fieldset><legend>기준 카테고리</legend><p>탐색 필터와 추천에서는 이 기준으로 분류해요.</p><div className="base-category-options">{TODO_CATEGORIES.map((item) => <button type="button" className={baseCategory === item ? "selected" : ""} aria-pressed={baseCategory === item} onClick={() => setBaseCategory(item)} key={item}>{item}{baseCategory === item && <Check aria-hidden />}</button>)}</div></fieldset><fieldset><legend>색상</legend><div className="category-color-options">{colors.map((item) => <button type="button" className={`category-swatch category-tone-${item.value} ${color === item.value ? "selected" : ""}`} aria-pressed={color === item.value} onClick={() => setColor(item.value)} key={item.value}><span />{item.label}{color === item.value && <Check aria-hidden />}</button>)}</div></fieldset>{error && <p className="form-error">{error}</p>}<button className="button full" disabled={saving}>{saving ? "저장 중…" : category ? "변경사항 저장" : "카테고리 만들기"}</button></form></Sheet>;
}

export default function TodoCategoriesPage() {
  const { status } = useSession(); const queryClient = useQueryClient();
  const [editor, setEditor] = useState<"new" | TodoCategoryDto | null>(null); const [showArchived, setShowArchived] = useState(false); const [notice, setNotice] = useState("");
  const categories = useQuery({ queryKey: ["todo-categories", showArchived], queryFn: () => apiFetch<TodoCategoryDto[]>(`/me/todo-categories${showArchived ? "?archived=true" : ""}`), enabled: status === "authenticated" });
  const update = useMutation({ mutationFn: ({ id, archived }: { id: string; archived: boolean }) => apiFetch(`/me/todo-categories/${id}`, { method: "PATCH", body: JSON.stringify({ archived }) }), onSuccess: (_data, input) => { setNotice(input.archived ? "카테고리를 보관했어요. 기존 TODO는 그대로 유지돼요." : "카테고리를 다시 사용해요."); void queryClient.invalidateQueries({ queryKey: ["todo-categories"] }); }, onError: (error) => setNotice(error instanceof Error ? error.message : "카테고리를 변경하지 못했어요.") });
  const reorder = useMutation({ mutationFn: (ids: string[]) => apiFetch<TodoCategoryDto[]>("/me/todo-categories/reorder", { method: "PATCH", body: JSON.stringify({ ids }) }), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["todo-categories"] }) });
  const move = (id: string, direction: -1 | 1) => { const active = (categories.data ?? []).filter((item) => !item.archivedAt); const index = active.findIndex((item) => item.id === id); const target = index + direction; if (index < 0 || target < 0 || target >= active.length) return; const next = [...active]; [next[index], next[target]] = [next[target], next[index]]; reorder.mutate(next.map((item) => item.id)); };
  const saved = () => { setEditor(null); setNotice("카테고리를 저장했어요."); void queryClient.invalidateQueries({ queryKey: ["todo-categories"] }); };
  if (status === "loading") return <main className="app-page"><ListSkeleton /></main>; if (status === "guest") return <main className="app-page"><AuthGate title="카테고리는 로그인 후 관리할 수 있어요" /></main>;
  const active = (categories.data ?? []).filter((item) => !item.archivedAt); const archived = (categories.data ?? []).filter((item) => item.archivedAt);
  return <main className="app-page todo-management-page"><header className="page-intro compact"><div><span>내 생활에 맞는 분류</span><h1>카테고리</h1></div><button className="round-button primary" onClick={() => setEditor("new")} aria-label="새 카테고리 만들기"><Plus /></button></header><TodoSectionNav /><section className="category-guide"><Tags aria-hidden /><div><b>기본 분류는 유지돼요</b><p>직접 만든 이름도 탐색에서는 8개 기준 카테고리 중 하나로 안전하게 연결돼요.</p></div></section>{notice && <button className="notice" onClick={() => setNotice("")}>{notice}</button>}{categories.isLoading ? <ListSkeleton /> : categories.isError ? <ErrorState onRetry={() => void categories.refetch()} /> : !active.length ? <EmptyState title="사용 중인 카테고리가 없어요" body="보관한 카테고리를 다시 켜거나 새로 만들어보세요." /> : <div className="category-manage-list">{active.map((item, index) => <article key={item.id}><span className={`category-manage-icon category-tone-${item.color}`}><Tags aria-hidden /></span><div><b>{item.name}</b><small>{item.isDefault ? "기본" : `${item.baseCategory} 기준`} · TODO {item.todoCount ?? 0}개</small></div><div className="category-order-actions"><button disabled={index === 0 || reorder.isPending} onClick={() => move(item.id, -1)} aria-label={`${item.name} 위로 이동`}><ArrowUp /></button><button disabled={index === active.length - 1 || reorder.isPending} onClick={() => move(item.id, 1)} aria-label={`${item.name} 아래로 이동`}><ArrowDown /></button></div>{!item.isDefault && <button className="category-row-action" onClick={() => setEditor(item)} aria-label={`${item.name} 편집`}><Pencil /></button>}<button className="category-row-action" onClick={() => update.mutate({ id: item.id, archived: true })} aria-label={`${item.name} 숨기기`}><EyeOff /></button></article>)}</div>}<button className="archived-category-toggle" onClick={() => setShowArchived((value) => !value)} aria-expanded={showArchived}>{showArchived ? <Eye /> : <Archive />}보관된 카테고리 {showArchived ? "접기" : "보기"}</button>{showArchived && archived.length > 0 && <div className="category-manage-list archived">{archived.map((item) => <article key={item.id}><span className="category-manage-icon"><Archive /></span><div><b>{item.name}</b><small>{item.baseCategory} 기준 · 기존 TODO 유지</small></div><button className="category-restore" onClick={() => update.mutate({ id: item.id, archived: false })}>다시 사용</button></article>)}</div>}{editor && <CategoryEditor category={editor === "new" ? null : editor} onClose={() => setEditor(null)} onSaved={saved} />}</main>;
}
