"use client";

import { FormEvent, Suspense, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, ChevronLeft, ChevronRight, Clock3, Ellipsis, ListPlus, Plus, Repeat2, Share2 } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import { apiFetch } from "@/lib/api";
import { koreanDate, localDateKey, monthRange, weekOf } from "@/lib/date";
import type { TodoDto, TodoListDto, Visibility } from "@/lib/types";
import { useSession } from "@/components/app-providers";
import { AuthGate, EmptyState, ErrorState, ListSkeleton } from "@/components/states";
import { TodoComposer, type TodoDraft } from "@/components/todo-composer";
import { ShareSheet } from "@/components/share-sheet";
import { Sheet } from "@/components/sheet";

export default function TodosPage() { return <Suspense fallback={<main className="app-page"><ListSkeleton /></main>}><TodosContent /></Suspense>; }

function TodosContent() {
  const { status } = useSession(); const params = useSearchParams(); const router = useRouter(); const queryClient = useQueryClient(); const today = localDateKey(); const selected = params.get("date") ?? today; const [calendar, setCalendar] = useState<"week" | "month">("week"); const [composer, setComposer] = useState(false); const [editing, setEditing] = useState<TodoDto | null>(null); const [listComposer, setListComposer] = useState(false); const [sharingList, setSharingList] = useState<TodoListDto | null>(null); const [notice, setNotice] = useState(params.get("imported") === "1" ? "가져온 실천을 내 TODO에 저장했어요." : "");
  const range = monthRange(selected);
  const todos = useQuery({ queryKey: ["todos", "month", range.from], queryFn: () => apiFetch<TodoDto[]>(`/todos?from=${range.from}&to=${range.to}`), enabled: status === "authenticated" });
  const lists = useQuery({ queryKey: ["todo-lists"], queryFn: () => apiFetch<TodoListDto[]>("/todo-lists"), enabled: status === "authenticated" });
  const create = useMutation({ mutationFn: (draft: TodoDraft) => apiFetch<TodoDto>("/todos", { method: "POST", body: JSON.stringify(draft) }), onSuccess: () => { setComposer(false); setNotice("TODO를 추가했어요."); void queryClient.invalidateQueries({ queryKey: ["todos"] }); } });
  const update = useMutation({ mutationFn: (draft: TodoDraft) => apiFetch<TodoDto>(`/todos/${editing?.id}`, { method: "PATCH", body: JSON.stringify(draft) }), onSuccess: () => { setEditing(null); setNotice("변경사항을 저장했어요."); void queryClient.invalidateQueries({ queryKey: ["todos"] }); } });
  const remove = useMutation({ mutationFn: () => apiFetch(`/todos/${editing?.id}`, { method: "DELETE" }), onSuccess: () => { setEditing(null); setNotice("TODO를 삭제했어요."); void queryClient.invalidateQueries({ queryKey: ["todos"] }); } });
  const complete = useMutation({ mutationFn: (todo: TodoDto) => apiFetch(`/todos/${todo.id}/complete`, { method: "POST", body: JSON.stringify({ share: false }) }), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["todos"] }) });
  const shareList = useMutation({ mutationFn: (data: { caption: string; visibility: Visibility; mediaKey?: string }) => apiFetch("/feed/posts", { method: "POST", body: JSON.stringify({ todoListId: sharingList?.id, ...data }) }), onSuccess: () => { setSharingList(null); setNotice("루틴을 공유했어요."); void queryClient.invalidateQueries({ queryKey: ["feed"] }); } });
  const rows = todos.data ?? []; const selectedRows = rows.filter((todo) => localDateKey(new Date(todo.dueDate)) === selected); const activeTodoId = selectedRows.find((todo) => !todo.completedAt)?.id; const week = weekOf(selected);
  const cursor = new Date(`${selected.slice(0, 7)}-01T12:00:00`); const first = cursor.getDay() === 0 ? 6 : cursor.getDay() - 1; const count = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 0).getDate(); const monthDays = [...Array(first).fill(null), ...Array.from({ length: count }, (_, index) => index + 1)];
  const chooseDate = (key: string) => { const next = new URLSearchParams(params.toString()); next.set("date", key); router.replace(`/todos?${next}`); };
  if (status === "loading") return <main className="app-page"><ListSkeleton /></main>; if (status === "guest") return <main className="app-page"><AuthGate title="내 캘린더는 로그인 후 사용할 수 있어요" /></main>;
  return <main className="app-page todos-page"><header className="page-intro compact"><div><span>계획은 가볍게, 기록은 차곡차곡</span><h1>TODO와 캘린더</h1></div><button className="round-button primary" onClick={() => setComposer(true)} aria-label="TODO 추가"><Plus /></button></header>
    <div className="calendar-switch"><button className={calendar === "week" ? "active" : ""} onClick={() => setCalendar("week")}>주간</button><button className={calendar === "month" ? "active" : ""} onClick={() => setCalendar("month")}>월간</button></div>
    <section className="calendar-card"><header><button aria-label="이전"><ChevronLeft /></button><b>{new Date(`${selected}T12:00:00`).toLocaleDateString("ko-KR", { year: "numeric", month: "long" })}</b><button aria-label="다음"><ChevronRight /></button></header>{calendar === "week" ? <div className="week-strip">{week.map((date) => { const key = localDateKey(date); const count = rows.filter((todo) => localDateKey(new Date(todo.dueDate)) === key).length; return <button key={key} className={key === selected ? "active" : ""} onClick={() => chooseDate(key)}><span>{date.toLocaleDateString("ko-KR", { weekday: "narrow" })}</span><b>{date.getDate()}</b>{count > 0 && <i />}</button>; })}</div> : <><div className="weekday-labels">{"월화수목금토일".split("").map((day) => <span key={day}>{day}</span>)}</div><div className="month-grid">{monthDays.map((day, index) => day ? <button key={day} className={selected.endsWith(`-${String(day).padStart(2, "0")}`) ? "active" : ""} onClick={() => chooseDate(`${selected.slice(0, 8)}${String(day).padStart(2, "0")}`)}>{day}{rows.some((todo) => localDateKey(new Date(todo.dueDate)) === `${selected.slice(0, 8)}${String(day).padStart(2, "0")}`) && <i />}</button> : <span key={`blank-${index}`} />)}</div></>}</section>
    {notice && <button className="notice" onClick={() => setNotice("")}>{notice}</button>}
    <div className="section-heading"><div><h2>{koreanDate(selected)}</h2><span>{selectedRows.length}개의 할 일</span></div><button className="soft-button" onClick={() => setComposer(true)}><Plus />추가</button></div>
    {todos.isLoading ? <ListSkeleton /> : todos.isError ? <ErrorState onRetry={() => void todos.refetch()} /> : selectedRows.length === 0 ? <EmptyState title="이날은 아직 비어 있어요" body="미리 계획하거나 편안한 여백으로 남겨두세요." /> : <section className="todo-stack compact">{selectedRows.map((todo) => <article className={`todo-item ${todo.completedAt ? "completed" : todo.id === activeTodoId ? "active" : "upcoming"}`} key={todo.id}><button className="todo-check" onClick={() => !todo.completedAt && complete.mutate(todo)} disabled={Boolean(todo.completedAt)}>{todo.completedAt && <Check />}</button><div><span><b>{todo.category}</b>{todo.repeatRule && <><Repeat2 />반복</>}</span><h3>{todo.title}</h3><small><Clock3 />{new Date(todo.dueDate).toLocaleTimeString("ko-KR", { hour: "2-digit", minute: "2-digit" })}</small></div><button className="icon-button" onClick={() => setEditing(todo)} aria-label={`${todo.title} 편집`}><Ellipsis /></button></article>)}</section>}
    <div className="section-heading spaced"><div><h2>나의 루틴 묶음</h2><span>한 번에 공유하고 가져와요</span></div><button className="soft-button" onClick={() => setListComposer(true)}><ListPlus />묶기</button></div>
    {lists.isLoading ? <ListSkeleton count={2} /> : (lists.data?.length ?? 0) === 0 ? <div className="inline-empty">자주 함께하는 TODO를 루틴으로 묶어보세요.</div> : <div className="routine-list">{lists.data?.map((list) => <article key={list.id}><span>{list.items.length}개의 TODO</span><h3>{list.title}</h3><p>{list.description || list.items.slice(0, 2).map((item) => item.todo.title).join(" · ")}</p><button onClick={() => setSharingList(list)}><Share2 />공유하기</button></article>)}</div>}
    {composer && <TodoComposer date={selected} busy={create.isPending} onClose={() => setComposer(false)} onSave={(draft) => create.mutate(draft)} />}{editing && <TodoComposer date={selected} todo={editing} busy={update.isPending || remove.isPending} onClose={() => setEditing(null)} onSave={(draft) => update.mutate(draft)} onDelete={() => remove.mutate()} />}{listComposer && <ListComposer todos={rows} busy={false} onClose={() => setListComposer(false)} onCreated={() => { setListComposer(false); void queryClient.invalidateQueries({ queryKey: ["todo-lists"] }); }} />}{sharingList && <ShareSheet list={sharingList} busy={shareList.isPending} onClose={() => setSharingList(null)} onShare={(data) => shareList.mutate(data)} />}
  </main>;
}

function ListComposer({ todos, busy, onClose, onCreated }: { todos: TodoDto[]; busy: boolean; onClose: () => void; onCreated: () => void }) {
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!selected.length) { setError("TODO를 하나 이상 선택해주세요."); return; } setSaving(true); try { await apiFetch("/todo-lists", { method: "POST", body: JSON.stringify({ title, description, todoIds: selected, visibility: "PRIVATE" }) }); onCreated(); } catch (cause) { setError(cause instanceof Error ? cause.message : "루틴을 만들지 못했어요."); } finally { setSaving(false); } };
  return <Sheet title="루틴 묶음 만들기" onClose={onClose}><form className="composer-form" onSubmit={submit}><label className="field"><span>루틴 이름</span><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="예: 퇴근 후 회복 루틴" maxLength={100} required /></label><label className="field"><span>짧은 설명</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} maxLength={300} placeholder="어떤 사람에게 도움이 되는 루틴인가요?" /></label><fieldset className="todo-picker"><legend>함께 묶을 TODO</legend>{todos.map((todo) => <label key={todo.id}><input type="checkbox" checked={selected.includes(todo.id)} onChange={() => setSelected((current) => current.includes(todo.id) ? current.filter((id) => id !== todo.id) : [...current, todo.id])} /><span>{todo.title}<small>{todo.category}</small></span></label>)}</fieldset>{error && <p className="form-error">{error}</p>}<button className="button full" disabled={busy || saving}>{saving ? "만드는 중…" : "루틴 묶음 만들기"}</button></form></Sheet>;
}
