"use client";

import { FormEvent, Suspense, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, ChevronDown, ChevronLeft, ChevronRight, Clock3, Ellipsis, ListPlus, Plus, Repeat2, Send } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import { apiFetch } from "@/lib/api";
import { koreanDate, localDateKey, monthRange, weekOf } from "@/lib/date";
import type { TodoDto, TodoListDto, Visibility } from "@/lib/types";
import { useSession } from "@/components/app-providers";
import { AuthGate, EmptyState, ErrorState, ListSkeleton } from "@/components/states";
import { TodoComposer, type TodoDraft } from "@/components/todo-composer";
import { PublishSheet } from "@/components/publish-sheet";
import { Sheet } from "@/components/sheet";
import { TodoGroupList } from "@/components/todo-group-list";

export default function TodosPage() { return <Suspense fallback={<main className="app-page"><ListSkeleton /></main>}><TodosContent /></Suspense>; }

function TodosContent() {
  const { status } = useSession(); const params = useSearchParams(); const router = useRouter(); const queryClient = useQueryClient(); const today = localDateKey(); const selected = params.get("date") ?? today; const [calendar, setCalendar] = useState<"week" | "month">("week"); const [composer, setComposer] = useState(false); const [editing, setEditing] = useState<TodoDto | null>(null); const [listComposer, setListComposer] = useState(false); const [editingList, setEditingList] = useState<TodoListDto | null>(null); const [sharingList, setSharingList] = useState<TodoListDto | null>(null); const [libraryOpen, setLibraryOpen] = useState(false); const [notice, setNotice] = useState(params.get("imported") === "1" ? "가져온 실천을 내 TODO에 저장했어요." : ""); const [deletedId, setDeletedId] = useState<string | null>(null);
  const range = monthRange(selected);
  const todos = useQuery({ queryKey: ["todos", "month", range.from], queryFn: () => apiFetch<TodoDto[]>(`/todos?from=${range.from}&to=${range.to}`), enabled: status === "authenticated" });
  const lists = useQuery({ queryKey: ["todo-lists"], queryFn: () => apiFetch<TodoListDto[]>("/todo-lists"), enabled: status === "authenticated" });
  const rows = todos.data ?? []; const linkedTodoId = params.get("todo"); const activeEditing = editing ?? rows.find((todo) => todo.id === linkedTodoId) ?? null;
  const closeEditor = () => { setEditing(null); if (linkedTodoId) { const next = new URLSearchParams(params.toString()); next.delete("todo"); router.replace(`/todos${next.size ? `?${next}` : ""}`); } };
  const create = useMutation({ mutationFn: (draft: TodoDraft) => apiFetch<TodoDto>("/todos", { method: "POST", body: JSON.stringify(draft) }), onSuccess: () => { setComposer(false); setNotice("TODO를 추가했어요."); void queryClient.invalidateQueries({ queryKey: ["todos"] }); void queryClient.invalidateQueries({ queryKey: ["todo-lists"] }); } });
  const update = useMutation({ mutationFn: (draft: TodoDraft) => apiFetch<TodoDto>(`/todos/${activeEditing?.id}`, { method: "PATCH", body: JSON.stringify(draft) }), onSuccess: () => { closeEditor(); setNotice("변경사항을 저장했어요."); void queryClient.invalidateQueries({ queryKey: ["todos"] }); void queryClient.invalidateQueries({ queryKey: ["todo-lists"] }); } });
  const remove = useMutation({ mutationFn: () => { const id = activeEditing?.id; if (!id) throw new Error("TODO를 찾지 못했어요."); return apiFetch(`/todos/${id}`, { method: "DELETE" }).then(() => id); }, onSuccess: (id) => { setDeletedId(id); closeEditor(); setNotice("TODO를 삭제했어요."); void queryClient.invalidateQueries({ queryKey: ["todos"] }); } });
  const restore = useMutation({ mutationFn: (id: string) => apiFetch(`/todos/${id}/restore`, { method: "POST" }), onSuccess: () => { setDeletedId(null); setNotice("삭제한 TODO를 복구했어요."); void queryClient.invalidateQueries({ queryKey: ["todos"] }); } });
  const complete = useMutation({ mutationFn: (todo: TodoDto) => apiFetch(`/todos/${todo.id}/complete`, { method: "POST", body: JSON.stringify({ share: false }) }), onMutate: async (todo) => { await queryClient.cancelQueries({ queryKey: ["todos"] }); const snapshots = queryClient.getQueriesData<TodoDto[]>({ queryKey: ["todos"] }); queryClient.setQueriesData<TodoDto[]>({ queryKey: ["todos"] }, (items) => items?.map((item) => item.id === todo.id ? { ...item, completedAt: new Date().toISOString() } : item)); return { snapshots }; }, onError: (_error, _todo, context) => context?.snapshots.forEach(([key, data]) => queryClient.setQueryData(key, data)), onSettled: () => void queryClient.invalidateQueries({ queryKey: ["todos"] }) });
  const uncomplete = useMutation({ mutationFn: (todo: TodoDto) => apiFetch(`/todos/${todo.id}/uncomplete`, { method: "POST" }), onMutate: async (todo) => { await queryClient.cancelQueries({ queryKey: ["todos"] }); const snapshots = queryClient.getQueriesData<TodoDto[]>({ queryKey: ["todos"] }); queryClient.setQueriesData<TodoDto[]>({ queryKey: ["todos"] }, (items) => items?.map((item) => item.id === todo.id ? { ...item, completedAt: null } : item)); return { snapshots }; }, onError: (_error, _todo, context) => context?.snapshots.forEach(([key, data]) => queryClient.setQueryData(key, data)), onSettled: () => void queryClient.invalidateQueries({ queryKey: ["todos"] }) });
  const endSeries = useMutation({ mutationFn: () => apiFetch(`/todos/${activeEditing?.id}/series`, { method: "DELETE" }), onSuccess: () => { closeEditor(); setNotice("이 날짜 이후의 반복을 종료했어요."); void queryClient.invalidateQueries({ queryKey: ["todos"] }); } });
  const publishList = useMutation({ mutationFn: (data: { caption: string; visibility: Visibility; hashtags: string[]; mediaId?: string }) => apiFetch("/feed/posts", { method: "POST", body: JSON.stringify({ todoListId: sharingList?.id, ...data }) }), onSuccess: () => { setSharingList(null); setNotice("루틴을 게시했어요."); void queryClient.invalidateQueries({ queryKey: ["feed"] }); } });
  const selectedRows = rows.filter((todo) => localDateKey(new Date(todo.dueDate)) === selected); const activeTodoId = selectedRows.find((todo) => !todo.completedAt)?.id; const week = weekOf(selected);
  const cursor = new Date(`${selected.slice(0, 7)}-01T12:00:00`); const first = cursor.getDay() === 0 ? 6 : cursor.getDay() - 1; const count = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 0).getDate(); const monthDays = [...Array(first).fill(null), ...Array.from({ length: count }, (_, index) => index + 1)];
  const chooseDate = (key: string) => { const next = new URLSearchParams(params.toString()); next.set("date", key); router.replace(`/todos?${next}`); };
  const moveCalendar = (direction: -1 | 1) => { const cursor = new Date(`${selected}T12:00:00`); if (calendar === "week") cursor.setDate(cursor.getDate() + direction * 7); else cursor.setMonth(cursor.getMonth() + direction); chooseDate(localDateKey(cursor)); };
  if (status === "loading") return <main className="app-page"><ListSkeleton /></main>; if (status === "guest") return <main className="app-page"><AuthGate title="내 캘린더는 로그인 후 사용할 수 있어요" /></main>;
  return <main className="app-page todos-page"><header className="page-intro compact"><div><span>계획은 가볍게, 기록은 차곡차곡</span><h1>내 TODO</h1></div><button className="round-button primary" onClick={() => setComposer(true)} aria-label="TODO 추가"><Plus /></button></header>
    <div className="calendar-switch"><button className={calendar === "week" ? "active" : ""} onClick={() => setCalendar("week")}>주간</button><button className={calendar === "month" ? "active" : ""} onClick={() => setCalendar("month")}>월간</button></div>
    <section className="calendar-card"><header><button aria-label="이전 기간" onClick={() => moveCalendar(-1)}><ChevronLeft /></button><b>{new Date(`${selected}T12:00:00`).toLocaleDateString("ko-KR", { year: "numeric", month: "long" })}</b><button aria-label="다음 기간" onClick={() => moveCalendar(1)}><ChevronRight /></button></header>{calendar === "week" ? <div className="week-strip">{week.map((date) => { const key = localDateKey(date); const count = rows.filter((todo) => localDateKey(new Date(todo.dueDate)) === key).length; return <button key={key} className={key === selected ? "active" : ""} onClick={() => chooseDate(key)}><span>{date.toLocaleDateString("ko-KR", { weekday: "narrow" })}</span><b>{date.getDate()}</b>{count > 0 && <i />}</button>; })}</div> : <><div className="weekday-labels">{"월화수목금토일".split("").map((day) => <span key={day}>{day}</span>)}</div><div className="month-grid">{monthDays.map((day, index) => day ? <button key={day} className={selected.endsWith(`-${String(day).padStart(2, "0")}`) ? "active" : ""} onClick={() => chooseDate(`${selected.slice(0, 8)}${String(day).padStart(2, "0")}`)}>{day}{rows.some((todo) => localDateKey(new Date(todo.dueDate)) === `${selected.slice(0, 8)}${String(day).padStart(2, "0")}`) && <i />}</button> : <span key={`blank-${index}`} />)}</div></>}</section>
    {notice && <div className="notice notice-action"><button onClick={() => setNotice("")}>{notice}</button>{deletedId && <button onClick={() => restore.mutate(deletedId)} disabled={restore.isPending}>{restore.isPending ? "복구 중…" : "되돌리기"}</button>}</div>}
    <div className="section-heading"><div><h2>{koreanDate(selected)}</h2><span>{selectedRows.length}개의 할 일</span></div><button className="soft-button" onClick={() => setComposer(true)}><Plus />추가</button></div>
    {todos.isLoading ? <ListSkeleton /> : todos.isError ? <ErrorState onRetry={() => void todos.refetch()} /> : selectedRows.length === 0 ? <EmptyState title="이날은 아직 비어 있어요" body="미리 계획하거나 편안한 여백으로 남겨두세요." /> : <TodoGroupList todos={selectedRows} lists={lists.data ?? []} onEditGroup={setEditingList} renderTodo={(todo) => <article className={`todo-item ${todo.completedAt ? "completed" : todo.id === activeTodoId ? "active" : "upcoming"}`} key={todo.id}><button className="todo-check" onClick={() => todo.completedAt ? uncomplete.mutate(todo) : complete.mutate(todo)} disabled={complete.isPending || uncomplete.isPending} aria-label={todo.completedAt ? `${todo.title} 완료 취소` : `${todo.title} 완료`}>{todo.completedAt && <Check />}</button><div><span><b>{todo.category}</b>{todo.repeatRule && <><Repeat2 />반복</>}</span><h3>{todo.title}</h3><small><Clock3 />{new Date(todo.dueDate).toLocaleTimeString("ko-KR", { hour: "2-digit", minute: "2-digit" })}</small></div><button className="icon-button" onClick={() => setEditing(todo)} aria-label={`${todo.title} 편집`}><Ellipsis /></button></article>} />}
    <div className="section-heading spaced routine-library-heading"><button className="routine-library-toggle" onClick={() => setLibraryOpen((current) => !current)} aria-expanded={libraryOpen}><div><h2>루틴 보관함</h2><span>{lists.data?.length ?? 0}개 묶음 · 관리하고 게시해요</span></div><ChevronDown className={libraryOpen ? "open" : ""} /></button><button className="soft-button" onClick={() => setListComposer(true)}><ListPlus />묶기</button></div>
    {libraryOpen && (lists.isLoading ? <ListSkeleton count={2} /> : (lists.data?.length ?? 0) === 0 ? <div className="inline-empty">자주 함께하는 TODO를 루틴으로 묶어보세요.</div> : <div className="routine-list">{lists.data?.map((list) => <article key={list.id}><span>{list.items.length}개의 TODO</span><h3>{list.title}</h3><p>{list.description || list.items.slice(0, 2).map((item) => item.todo.title).join(" · ")}</p><div className="routine-actions"><button onClick={() => setEditingList(list)}><Ellipsis />관리</button><button onClick={() => setSharingList(list)}><Send />루틴 게시하기</button></div></article>)}</div>)}
    {composer && <TodoComposer date={selected} lists={lists.data ?? []} busy={create.isPending} onClose={() => setComposer(false)} onSave={(draft) => create.mutate(draft)} />}{activeEditing && <TodoComposer date={selected} todo={activeEditing} lists={lists.data ?? []} busy={update.isPending || remove.isPending || endSeries.isPending} onClose={closeEditor} onSave={(draft) => update.mutate(draft)} onDelete={() => remove.mutate()} onEndSeries={() => endSeries.mutate()} />}{listComposer && <ListComposer todos={rows} lists={lists.data ?? []} busy={false} onClose={() => setListComposer(false)} onSaved={() => { setListComposer(false); setNotice("새 루틴 그룹을 만들었어요."); void queryClient.invalidateQueries({ queryKey: ["todo-lists"] }); }} />}{editingList && <ListComposer todos={rows} lists={lists.data ?? []} list={editingList} busy={false} onClose={() => setEditingList(null)} onSaved={() => { setEditingList(null); setNotice("루틴 그룹을 정리했어요."); void queryClient.invalidateQueries({ queryKey: ["todo-lists"] }); }} />}{sharingList && <PublishSheet list={sharingList} busy={publishList.isPending} onClose={() => setSharingList(null)} onPublish={(data) => publishList.mutate(data)} />}
  </main>;
}

function ListComposer({ todos, lists, list, busy, onClose, onSaved }: { todos: TodoDto[]; lists: TodoListDto[]; list?: TodoListDto; busy: boolean; onClose: () => void; onSaved: () => void }) {
  const availableTodos = [...(list?.items.map((item) => item.todo) ?? []), ...todos].filter((todo, index, all) => all.findIndex((candidate) => candidate.id === todo.id) === index);
  const occupied = lists.filter((candidate) => candidate.id !== list?.id).flatMap((candidate) => candidate.items.map((item) => item.todo));
  const unavailable = (todo: TodoDto) => occupied.some((item) => item.id === todo.id || Boolean(item.seriesId && item.seriesId === todo.seriesId));
  const [title, setTitle] = useState(list?.title ?? ""); const [description, setDescription] = useState(list?.description ?? ""); const [selected, setSelected] = useState<string[]>(list?.items.map((item) => item.todo.id) ?? []); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!selected.length) { setError("TODO를 하나 이상 선택해주세요."); return; } setSaving(true); try { await apiFetch(list ? `/todo-lists/${list.id}` : "/todo-lists", { method: list ? "PATCH" : "POST", body: JSON.stringify({ title, description, todoIds: selected, visibility: "PRIVATE" }) }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "루틴을 저장하지 못했어요."); } finally { setSaving(false); } };
  return <Sheet title={list ? "루틴 그룹 관리" : "루틴 묶음 만들기"} onClose={onClose}><form className="composer-form" onSubmit={submit}><label className="field"><span>루틴 이름</span><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="예: 퇴근 후 회복 루틴" maxLength={100} required /></label><label className="field"><span>짧은 설명</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} maxLength={300} placeholder="어떤 실천을 함께 묶었는지 적어보세요." /></label><fieldset className="todo-picker"><legend>함께 묶을 TODO</legend>{availableTodos.map((todo) => { const disabled = unavailable(todo); return <label className={disabled ? "unavailable" : ""} key={todo.id}><input type="checkbox" disabled={disabled} checked={selected.includes(todo.id)} onChange={() => setSelected((current) => current.includes(todo.id) ? current.filter((id) => id !== todo.id) : [...current, todo.id])} /><span>{todo.title}<small>{disabled ? "다른 그룹에 포함됨" : todo.category}</small></span></label>; })}</fieldset>{error && <p className="form-error">{error}</p>}<button className="button full" disabled={busy || saving}>{saving ? "저장 중…" : list ? "그룹 변경사항 저장" : "루틴 묶음 만들기"}</button></form></Sheet>;
}
